#+title: chee

#+attr_html: style="display:inline;"
https://travis-ci.org/eikek/chee.svg

Chee is a command line tool for managing photos; also called “image
organizer”.

Some features are:

- search photos using a simple query language by file and image
  properties (resolution, created-time, etc)
- manages collections (created from queries and can be used in
  queries)
- copy/symlink images using a custom pattern: keep original files
  where they are and create symlink trees using a custom folder
  structure
- create thumbnails or scaled versions (creates new files, original
  files are not touched)

It is a simple program: the metadata of image (and other) files are
put in a database which can then be queried more conveniently. But
this already allows some useful features.

It is written in Scala and runs on the JVM so it is quite platform
neutral. Chee allows to query and print information from the database
in very flexible ways. Still, in case you need raw data access, simply
look at the [[http://sqlite.org][sqlite]] database with other tools (such as sqlite command
line tool or [[http://sqliteman.com][sqliteman]]).

* Installing

** Building

[[http://scala-sbt.com][sbt]] and Java 8 is used for building (and Java 8 running) chee. Install
jdk8 and sbt, then clone the repository and execute:

#+begin_src shell :exports code
sbt make-zip
#+end_src

in the source root. The result is a zip file in =target=
folder. Unpack the zip somewhere and add the resulting directory to
your =PATH=. Then the ~chee~ command should be available. Test it via

#+begin_src shell :exports code
chee version
#+end_src

** Using Nix

You can build chee with the [[http://nixos.org/nix][nix package manager]].

#+begin_src shell :exports both
nix-build https://github.com/eikek/chee/archive/release/0.1.0.tar.gz
#+end_src

or install it with

#+begin_src shell :exports code
nix-env -if https://github.com/eikek/chee/archive/release/0.1.0.tar.gz
#+end_src

** Download

Prebuild zip files are usually available for download here:

- [[https://eknet.org/main/projects/chee/chee-0.1.0.zip][current]]

Download and unzip the file. Then add the resulting directory to your
~$PATH~. You need Java 8 for running it. Test it via

#+begin_src shell :exports code
chee version
#+end_src

* Documentation

Chee is a command line tool and comes with documentation built in. It
is accessible via the ~help~ command.

The help command provides information about chee's concepts as well as
about its commands. Help pages can be printed to stdout or viewed in a
browser. Run ~chee help~ to find out more.

The command

#+begin_src shell :exports code
chee help manual
#+end_src

opens a browser showing the complete manual.

Click [[https://eknet.org/main/projects/chee/manual-0.1.0.html][here]] to read the manual now.
