=== Configuration

This documents how chee is configured.

Chee reads a configuration file from the following locations:

- `$HOME`/.chee.conf
- `$HOME`/.config/chee/chee.conf

The first existing file is used. This is the user configuration. Chee
never writes to this file, it is only read on start. But another
config file is created (by default at `$HOME/.config/chee/system.cfg`)
where chee stores data.

A config file can be in three formats:

- java properties
- json
- hocon (a json superset)

The HOCON format is probably the most convenient of the three for us
humans. Here is the default config file in HOCON format:

.Default Config File
----------------------------------------------------------------------
<chee_configfile>
----------------------------------------------------------------------

The HOCON format allows to create a hierarchical layout, where a key
is a path. Path elements are separated by a dot `.`. So writing

----------------------------------------------------------------------
chee {
  formats {
    key = "test"
  }
}
----------------------------------------------------------------------

is the same as

----------------------------------------------------------------------
chee {
  formats.key = "test"
}
----------------------------------------------------------------------

or

----------------------------------------------------------------------
chee.formats.key = "test"
----------------------------------------------------------------------

This way it translates easily into java property files. More detailed
information about the HOCON format can be found
https://github.com/typesafehub/config#using-hocon-the-json-superset[here]
and in its
https://github.com/typesafehub/config/blob/master/HOCON.md[specification].

All config values are inside the `chee { … }` namespace. The two
important properties are `workingdir` and `configdir`. The first
defines the directory where chee can store work-data. The latter names
a directory where chee stores user data. The difference is that
`workingdir` contains data that can be removed without really loosing
information. For instance, the index database is stored at
`workingdir`, because it can be derived from the image files. And
`configdir` contains user data that cannot be deleted safely.

Any value in the config file can be overridden by a system property.


==== Repository Mode

You can restrict chee to work only on a specific folder, the
repository. A repository is a directory that has a `.chee` directory
as its direct child. So a repository can be created by simply doing
`mkdir .chee`.

On start chee looks for a `.chee` directory in the current working
directory and above. If it is found, the chee configures itself by
setting `chee.configdir` to `.chee` and `chee.workingdir` to
`.chee/work`. The configuration file is read from
`.chee/chee.conf`. If a config file doesn't exists, an empty one is
used.

The repository is isolated from global chee data and only directories
below the repository folder can be added. The repository contains the
images as well as chee data and can be moved around in the file
system. When files inside a repository are indexed, file names
relative to the repository root are stored.

By default only directories inside the repository can be added as
locations. But this check can be removed by setting
`chee.repo.restrict-to-root` to `false` (in `.chee/chee.conf`). Note
that this breaks the isolation, because the index must use absolute
paths to reference files outside the repository. This means the
repository cannot be renamed or moved around.


==== Logging

Logging is configured via another configuration file that is by
default at `${chee.configdir}/logback.xml`. If this file does not
exist, chee simply logs into a logfile. Only very few logging is done
by default.

Two things can be controlled via the configuration file: where the log
file should be (key `chee.logFile`) and the log level (key
`chee.logLevel`). The log file is by default in chee's `workingdir`
and the default log level is `INFO`. This logs only very little. If
you encounter strange behaviour, try setting the `chee.logLevel` to
`DEBUG` or even `TRACE` to see more log output. If you set it to
`OFF`, no logging is done.

You can also specify a custom logging configuration by providing a
`logback.xml` file. How logging can be configured is beyond the scope
of this manual. You can read it up
http://logback.qos.ch/manual/configuration.html[here].


==== System Properties

System properties can be specified by using the environment variable
`CHEE_OPTS`. This is added to the java command that starts chee. It
can be used to override config values for the next run of chee.

For example to change the log level, you could do

----------------------------------------------------------------------
CHEE_OPTS=-Dchee.logLevel=TRACE chee find …
----------------------------------------------------------------------

Since the configuration file is used to configure logging, the process
that reads the configuration cannot log itself. If you like to see
which file chee is really reading, set a system property
`chee.debugConfig=true`.

.Example
----------------------------------------------------------------------
CHEE_OPTS=-Dchee.debugConfig=true chee config
----------------------------------------------------------------------


==== Custom config file

You can skip chee config file lookup by specifying a config file using
the system property `chee.config`. If you specify a non-existing file,
an empty configuration is used. This will always override any other
config file, be it a `.chee` or the global one.
