=== collection

Manages collections. The collection command requires subcommands.

.Usage
----------------------------------------------------------------------
collection [edit|show]
----------------------------------------------------------------------


==== edit

Edits a collection or creates a new one.

.Usage
----------------------------------------------------------------------
<usage_collection_edit>
----------------------------------------------------------------------

The argument is mandatory and names the collection to edit. If the
name is unknown, a new one is created with that name.

The command works interactively and non-interactively. If a value for
`name`, `query` or `description` is given, it is set into the
collection silently. Otherwise an external editor opens to allow
changing or creating a collection.

The editor is filled with a template. You can specify the name, query
and a description. When the file is saved and the editor exists, the
text is saved to the list of collections. If you leave the name or
query empty, the process is cancelled and the collection list is not
updated.

The editor program is determined from the configuration file. Set a
program at key `chee.programs.editor`. If this is not set, the
environment variable `EDITOR` is used. If this is empty, too, an error
is reported.

==== show

Shows details about collections.

.Usage
----------------------------------------------------------------------
<usage_collection_show>
----------------------------------------------------------------------


By default it lists all collections with name and title, one per line.

A xref:_format_pattern[Format Pattern] can be used to customize the
output. There are the same predefined patterns as with the `find`
command: `oneline` (the default), `detail` and `lisp`. If the pattern
is not one of these, it is tried to find in the configuration file or
used as a pattern itself.

The `detail` pattern prints all details about an collection. The
properties to use in the format pattern are: `name`, `title`, `query`
and `description`.

The argument is a portion of a name to restrict the output to only
those collection that start with `\<name>`. If not given, all
collections are listed.
