=== gallery

Create a html photo gallery.

.Usage
----------------------------------------------------------------------
<usage_gallery>
----------------------------------------------------------------------

.Example
----------------------------------------------------------------------
chee gallery 'date:201410*'
chee gallery --out gallery.zip 'date:201410*'
----------------------------------------------------------------------

This command generates a html page containing an image gallery. The
image gallery is provided by the well known
http://getbootstrap.com[bootstrap] and
https://github.com/blueimp/Bootstrap-Image-Gallery[bootstrap gallery]
css and javascript libraries.

The `--theme` option can be used to select a theme for the html
page. This just selects a css file from one of the collection at
http://bootswatch.com[bootswatch]. The default theme is `bootstrap`
which is the standard bootstrap look. The default template contains
only the thumbnail list, so using a theme becomes more useful with
custom templates.

The images to use for the gallery are selected using a query, like
with `view` and `find` commands. Then the query is constrained to only
select image files by appending a query condition from the config
file.

<transparent_decrypt>
If `--out` is specified, all resources and images are placed into this
folder. It is then possible to transfer this folder to somewhere else
and view the gallery page. If `--out` is not specified, the page is
generated in a temporary directory and images are linked directly to
its original location. This makes it a little faster to generate the
gallery as images don't need to be copied.

By default, images are scaled such that the longest side is at most
1400px. This is to reduce bandwidth and improve responsiveness when
viewing it over the internet. With `--no-scale` this can be
skipped. In this case the original image files are used unscaled.

With `--link-original` the page provides a donwload link to download
the original image file (when scaled images are used, it may be
desireable to access the original unscaled image nevertheless). The
`--title` option can be used to set the title in the html file. Any
other customization must be done by using a custom template.

The page is generated by expanding a
http://mustache.github.io[mustache] template. A custom template can be
given by the `--template` option. For an easy start,
`--write-template` saves the default template to a file for you to
edit. The template is supplied the following object:

* `files` - an array of objects for each image file:
   - it contains all xref:_properties[file properties] plus
   - `thumbnail` refers to the thumbnail path
   - `scaled-image` refers to the scaled image. If `--no-scale` is in
     effect, this is an alias to `path`
   - `_format` this is a special function that parses its body as a
     format pattern and applies to it the current map. See
     xref:_format_patterns[Format Patterns] section for details. This
     is useful when rendering human readable values of certain
     properties. Example: `{{#_format}}~:length{{/_format}}` would
     render the file size in human readable form.
* `link-original` a boolean refering to the same named option
* `title` a string refering to the same named option
* `js` an array of all javascript urls
* `css` an array of all css urls
* `projectInfo` an object containing information about chee
   - `name` the project name “chee“
   - `version` chee version
   - `homepage` url to the homepage of chee

The default template renders a simple photo gallery: a list of
thumbnails and a detail view for each picture. When on detail view,
the image description can be turned on and off by clicking into the
image or by pressing ENTER. Custom metadata (tags and comments) are
rendered in the detail view. The comment is treated as markdown and
converted into html.

Please see the http://mustache.github.io/mustache.5.html[mustache syntax
documentation] for an explanation of its syntax.
