=== mktree

Copies or symlinks a set of files into another directory.

.Usage
----------------------------------------------------------------------
<usage_mktree>
----------------------------------------------------------------------

To select the files to symlink or copy, the same options as for the
`find` command are used. Additionally, there are options that control
the target filename and whether to overwrite existing files or not.

The `--overwrite` option tells chee to overwrite existing files. By
default, they are skipped.

The `--pattern` option is used to determine the target filename. This
is a xref:_format_patterns[format pattern] and the default value
will make a filename like this:
`\<year>/\<month>/\<day>-\<hour>-\<minute>_\<filename>`. That is, files are
sorted in a directory structure based on their `created` or
`lastmodified` property. As with the `find` command, you can specify a
pattern at the command line or refer to a pattern from the config
file under the key `chee.formats`.

The `--target` option specifies the directory to transfer
files to. The name that results from `--pattern` is appended to
this. It is by default the current working directory. If a target
directory does not exist, it is created.

Only one action option (symlink, relative symlink or copy) should be
specified, if more are given, the last option wins.

<transparent_decrypt>

The `query` argument is the query string that is run against the index
or a directory (if `-f` is given). See xref:_query[query] concept page
for details.

.Symlink files with default pattern
----------------------------------------------------------------------
$ chee mktree -u --target sorted/ --first 10 'make:nikon*'
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6248.JPG → /home/eike/testdir/pics/sorted/2015/06/22-17-31_DSC_6248.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6259.JPG → /home/eike/testdir/pics/sorted/2015/06/22-17-48_DSC_6259.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6261.JPG → /home/eike/testdir/pics/sorted/2015/06/22-17-48_DSC_6261.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6262.JPG → /home/eike/testdir/pics/sorted/2015/06/22-17-48_DSC_6262.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6265.JPG → /home/eike/testdir/pics/sorted/2015/06/22-18-02_DSC_6265.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6283.JPG → /home/eike/testdir/pics/sorted/2015/07/07-19-21_DSC_6283.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6285.JPG → /home/eike/testdir/pics/sorted/2015/07/07-19-22_DSC_6285.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6288.JPG → /home/eike/testdir/pics/sorted/2015/07/07-19-22_DSC_6288.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6293.JPG → /home/eike/testdir/pics/sorted/2015/07/09-18-01_DSC_6293.JPG … Ok
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6305.JPG → /home/eike/testdir/pics/sorted/2015/07/18-14-45_DSC_6305.JPG … Ok
10 files processed in 0:00:00.108
----------------------------------------------------------------------

If no pattern is specified, chee uses a default pattern that sorts
images according to their creation timestamp. If that's not available,
the last modification timestamp of the file is used. Images are sorted
into folders by month and prefixed with the day, hour and minute. The
first picture in the example output above was taken on
2015/06/22 17:31.

The resulting directory structure of the example above is:

.Structure
----------------------------------------------------------------------
$ tree sorted/
sorted/
└── 2015
    ├── 06
    │   ├── 22-17-31_DSC_6248.JPG -> ../../../repo2/DSC_6248.JPG
    │   ├── 22-17-48_DSC_6259.JPG -> ../../../repo2/DSC_6259.JPG
    │   ├── 22-17-48_DSC_6261.JPG -> ../../../repo2/DSC_6261.JPG
    │   ├── 22-17-48_DSC_6262.JPG -> ../../../repo2/DSC_6262.JPG
    │   └── 22-18-02_DSC_6265.JPG -> ../../../repo2/DSC_6265.JPG
    └── 07
        ├── 07-19-21_DSC_6283.JPG -> ../../../repo2/DSC_6283.JPG
        ├── 07-19-22_DSC_6285.JPG -> ../../../repo2/DSC_6285.JPG
        ├── 07-19-22_DSC_6288.JPG -> ../../../repo2/DSC_6288.JPG
        ├── 09-18-01_DSC_6293.JPG -> ../../../repo2/DSC_6293.JPG
        └── 18-14-45_DSC_6305.JPG -> ../../../repo2/DSC_6305.JPG

3 directories, 10 files
----------------------------------------------------------------------

A custom pattern can be specified with `--pattern`. This can get quite
complex, but patterns can be bookmarked in the configuration file and
refered to by name.

.Symlink files using custom pattern
----------------------------------------------------------------------
$ chee mktree -u --target sorted/ --first 10 --pattern '~:ext/~[created~;~#cr~fE~;~#l~fE~]/~#file' 'make:nikon*'
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6248.JPG → /home/eike/testdir/pics/sorted/JPG/Mon/DSC_6248.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6259.JPG → /home/eike/testdir/pics/sorted/JPG/Mon/DSC_6259.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6261.JPG → /home/eike/testdir/pics/sorted/JPG/Mon/DSC_6261.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6262.JPG → /home/eike/testdir/pics/sorted/JPG/Mon/DSC_6262.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6265.JPG → /home/eike/testdir/pics/sorted/JPG/Mon/DSC_6265.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6283.JPG → /home/eike/testdir/pics/sorted/JPG/Tue/DSC_6283.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6285.JPG → /home/eike/testdir/pics/sorted/JPG/Tue/DSC_6285.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6288.JPG → /home/eike/testdir/pics/sorted/JPG/Tue/DSC_6288.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6293.JPG → /home/eike/testdir/pics/sorted/JPG/Thu/DSC_6293.JPG … Skipped
RelativeSymlink /home/eike/testdir/pics/repo2/DSC_6305.JPG → /home/eike/testdir/pics/sorted/JPG/Sat/DSC_6305.JPG … Skipped
10 files processed in 0:00:00.69
----------------------------------------------------------------------

The pattern results in a folder per extension and weekday. The `~:ext`
refers to the file extension. Then the timestamp is either taken from
the `created` property, or if that does not exist, from the
`lastmodified` property. The names are abbreviated to `cr` and
`l`. The `~fE` applies a format to the timestamp that results in the
weekday. And at last the `filename` is appended.

.Structure
----------------------------------------------------------------------
$ tree sorted/
sorted/
└── JPG
    ├── Mon
    │   ├── DSC_6248.JPG -> ../../../repo2/DSC_6248.JPG
    │   ├── DSC_6259.JPG -> ../../../repo2/DSC_6259.JPG
    │   ├── DSC_6261.JPG -> ../../../repo2/DSC_6261.JPG
    │   ├── DSC_6262.JPG -> ../../../repo2/DSC_6262.JPG
    │   └── DSC_6265.JPG -> ../../../repo2/DSC_6265.JPG
    ├── Sat
    │   └── DSC_6305.JPG -> ../../../repo2/DSC_6305.JPG
    ├── Thu
    │   └── DSC_6293.JPG -> ../../../repo2/DSC_6293.JPG
    └── Tue
        ├── DSC_6283.JPG -> ../../../repo2/DSC_6283.JPG
        ├── DSC_6285.JPG -> ../../../repo2/DSC_6285.JPG
        └── DSC_6288.JPG -> ../../../repo2/DSC_6288.JPG
----------------------------------------------------------------------
