=== mv

Moves files and directories.

.Usage
----------------------------------------------------------------------
<usage_mv>
----------------------------------------------------------------------

The `mv` moves (or renames) files and synchronises the index
accordingly. It works only for files that are known to chee (are
indexed). Otherwise, use import or add to add files to the index.

Multiple source files can be specified. The last file is the
target. The target must be an existing directory if multiple source
files are specified.

Here are some examples:

.Move files
----------------------------------------------------------------------
chee mv DSC_7600.JPG dsc_7600_1.jpg
----------------------------------------------------------------------

This renames the file to lowercase. The same is used to rename
directories.

.Move multiple files in a directory
----------------------------------------------------------------------
chee mv loc1/*.jpg loc1/old
----------------------------------------------------------------------

The target `loc1/old` must be an existing directory. The `loc1/*.jpg`
uses shell expansion to get all files with a `jpg` extension to move
them in the folder `old`.

.Move directory (1)
----------------------------------------------------------------------
chee mv loc1/sdcard0 loc2/
----------------------------------------------------------------------

This moves the directory `sdcard0` into another one `loc2`. Since
`loc2` exists, the directory `loc2/sdcard0` is created.


.Rename a directory (2)
----------------------------------------------------------------------
chee mv loc1/ newloc/
----------------------------------------------------------------------

This moves the directory `loc1` to a new one `newloc`. Since `loc1` is
indexed, the directory is renamed and the index is updated such that
path and location properties point to the new one `newloc`.


