=== decrypt

Dencrypt files using a password or a public key.

[subs="attributes,specialchars"]
.Usage
----------------------------------------------------------------------
{usage-decrypt}
----------------------------------------------------------------------

.Example
----------------------------------------------------------------------
chee decrypt encrypted?
----------------------------------------------------------------------

This example decrypts all encrypted files.

The _Find options_ are for selecting encrypted files to decrypt. These
are the same as with the `find` command.

The files are encrypted using http://openpgp.org[OpenPGP] and there
are two possible ways:

- public key, so decryption requires the corresponding private key
- using a password for decryption

The `--method` option chooses one of the two. Its value can also be
specified in the config file and the default value is `pubkey`.

For `pubkey` encryption, a `--key-file` and `--secret-key-pass` must
be specified. The key file must be in OpenPGP format. The
`secret-key-pass` file must be a file where the first line contains
the password to access the private key.

For `password` based encryption, the passphrase can be typed in or
read from a file.  A default password can be set in the configuration
file which is used if no `--passhprase` is given, unless `-W` is
specified that will always prompt for a passphrase.

Please see the xref:_configuration[configuration] chapter for related
configuration values and the page about xref:_encryption[encryption].
