Chee- Photo Organizer (<version>)
=====================================
Eike Kettner
v<version> (build <commit> at <buildtime>)
:toc: true
:toclevels: 3
:toc-placement: top

Chee is a command line tool for managing and organizing photos.

How do you organize your photos? I have a bunch of folders with
contents from various flash cards, because manually sorting alot of
photos is too time consuming. Chee wants to help at this point. It can
search photos from different directories by querying its image
metadata. So the idea is to simply keep these flash card dumps and
work with them.

Some features are:

- no “application lock-in”; chee uses open formats for storing data so
  that it can be easily accessed using other (free or open-source)
  tools
- search photos using a simple query language
- manage named queries (called collections)
- copy/symlink images into a custom folder structure
- create thumbnails or scaled versions (creates new files, original
  files are not touched)
- encrypt files using OpenPGP
- tag and comment photos
- create static html photo gallery

It is a simple program: the metadata of image (and other) files are
put in a database which can then be queried more conveniently. But
this already allows some useful features.

It is written in Scala and runs on the JVM so it is quite platform
neutral. Chee uses two databases: sqlite for file metadata and a
https://www.gnu.org/software/recutils/[rec] file for user metadata
(tags and comments). It allows to query and print information from the
database in very flexible ways. Still, in case you need raw data
access, use sqlite cli tool or http://sqliteman.com[sqliteman] to look
at the http://sqlite.org[sqlite] database and
https://www.gnu.org/software/recutils/[rec utilities] or any text
editor to access user metadata.


== Concepts

include::about-property.adoc[]

include::about-location.adoc[]

include::about-query.adoc[]

include::about-collection.adoc[]

include::about-format.adoc[]

include::about-metadata.adoc[]

include::about-encryption.adoc[]

include::about-config.adoc[]


== Commands

include::cmd-help.adoc[]

include::cmd-find.adoc[]

include::cmd-view.adoc[]

include::cmd-gallery.adoc[]

include::cmd-add.adoc[]

include::cmd-import.adoc[]

include::cmd-sync.adoc[]

include::cmd-info.adoc[]

include::cmd-meta.adoc[]

include::cmd-mv.adoc[]

include::cmd-rm.adoc[]

include::cmd-collection.adoc[]

include::cmd-mktree.adoc[]

include::cmd-thumb.adoc[]

include::cmd-scale.adoc[]

include::cmd-encrypt.adoc[]

include::cmd-decrypt.adoc[]

include::cmd-clean.adoc[]

include::cmd-config.adoc[]
