Chee- Photo Organizer (<version>)
============================
Eike Kettner
v<version> (build <commit> at <buildtime>)

Chee is a command line tool for managing and organizing photos.

How do you organize your photos? I have a bunch of folders with
contents from various flash cards, because manually sorting alot of
photos is too time consuming. Chee wants to help at this point. It can
search photos from different directories by querying its image
metadata. So the idea is to simply keep these flash card dumps and
work with them.

Some features are:

- No “application lock-in”; chee uses open formats for storing data so
  that it can be easily accessed using other (free or open-source)
  tools. For example, OpenPGP is used for encryption so the data
  remains accessible using tools like gnupg. The metadata derived from
  files is stored in an sqlite db for which many tools exists to
  access its data.
- search photos using a simple query language by file and image
  properties (resolution, created-time, etc)
- manages collections (created from queries and can be used in
  queries)
- copy/symlink images using a custom pattern: keep original files
  where they are and create symlink trees using a custom folder
  structure
- create thumbnails or scaled versions (creates new files, original
  files are not touched)
- encrypt files using a password or a public key. Encryption is done
  via OpenPGP.
- tag and comment photos: user metadata (tags and comments) is stored
  in a https://www.gnu.org/software/recutils/[rec] plain text
  file. That allow to edit it manually or use the
  https://www.gnu.org/software/recutils/[rec utilities] to access the
  data.

It is a simple program: the metadata of image (and other) files are
put in a database which can then be queried more conveniently. But
this already allows some useful features.


== Concepts

include::about-property.adoc[]

include::about-location.adoc[]

include::about-query.adoc[]

include::about-collection.adoc[]

include::about-format.adoc[]

include::about-metadata.adoc[]

include::about-encryption.adoc[]

include::about-config.adoc[]


== Commands

include::cmd-help.adoc[]

include::cmd-find.adoc[]

include::cmd-view.adoc[]

include::cmd-location.adoc[]

include::cmd-meta.adoc[]

include::cmd-mv.adoc[]

include::cmd-rm.adoc[]

include::cmd-collection.adoc[]

include::cmd-mktree.adoc[]

include::cmd-thumb.adoc[]

include::cmd-scale.adoc[]

include::cmd-encrypt.adoc[]

include::cmd-decrypt.adoc[]

include::cmd-clean.adoc[]

include::cmd-config.adoc[]
